version: '3.5'
services:
  mybook-api:
    container_name: mybook-api
    build:
      context: ./
      dockerfile : Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - spring-network
  db:
    image: mariadb:10.8.2-focal
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mybooks
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  spring-network:
    driver : bridge
    name: spring-network

